# Generated by Django 4.1.7 on 2024-12-27 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('hname', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('postoffice', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('type', models.CharField(default='client', max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_images/')),
                ('aadharno', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
