# Generated by Django 4.1.7 on 2025-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='reply_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
