# Generated by Django 4.1.7 on 2024-12-23 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('officename', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('postoffice', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('contactno', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('aadharno', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
