# Generated by Django 4.1.7 on 2025-01-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0002_specializations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateregistration',
            name='admin_approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('not approved', 'Not Approved')], default='not approved', max_length=20),
        ),
    ]
