# Generated by Django 4.1.7 on 2024-12-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advocate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('case_des', models.TextField()),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('cust_approval', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advocate.advocateregistration')),
            ],
        ),
    ]
