# Generated by Django 4.1.7 on 2025-01-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
